/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;

//import java.lang.annotation.Annotation;
import java.io.*;
import java.util.Random;

public class App {

    public static void main(String[] args) {
        Quote showQuote = jsonReader();
        System.out.println(showQuote);

    }

    //need to write a method to read the quotes file
    public static Quote jsonReader() {
        BufferedReader reader = null;
        try {
            reader = new BufferedReader(new FileReader("quotes.json"));
            Gson gson = new Gson();
            Quote[] resultingQuote = gson.fromJson(reader, Quote[].class);

            Random rand = new Random();
            int num = rand.nextInt(resultingQuote.length);
            return resultingQuote[num];

        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }
        finally{
            try {
                reader.close();
            } catch (IOException e) {
                e.printStackTrace();
            }
    }
        return null;
    }
}
